import React, { useState } from 'react'
import {
  View, Text, StyleSheet, ScrollView,
  TouchableOpacity, Alert, ActivityIndicator, SafeAreaView
} from 'react-native'
import { LinearGradient } from 'expo-linear-gradient'
import { colors } from '../theme/colors'

export default function DemandLetterScreen({ route, navigation }: any) {
  const { analysis } = route.params
  const letter: string = analysis.demand_letter
  const [generatingPdf, setGeneratingPdf] = useState(false)

  const handleExport = async () => {
    setGeneratingPdf(true)
    try {
      const RNHTMLtoPDF = require('react-native-html-to-pdf').default
      const Share = require('react-native-share').default

      const html = `
        <html>
          <head>
            <style>
              body { font-family: Georgia, serif; font-size: 14px; line-height: 1.8;
                     margin: 60px; color: #1a1a1a; }
              p { margin: 0 0 16px 0; }
              .disclaimer { margin-top: 40px; font-size: 11px; color: #888;
                           border-top: 1px solid #eee; padding-top: 16px; }
            </style>
          </head>
          <body>
            ${letter.split('\n').map((line: string) => `<p>${line || '&nbsp;'}</p>`).join('')}
            <div class="disclaimer">
              Generated by Advocate App. This letter is provided for informational purposes only
              and does not constitute legal advice.
            </div>
          </body>
        </html>
      `
      const pdf = await RNHTMLtoPDF.convert({
        html,
        fileName: `advocate-demand-letter-${Date.now()}`,
        directory: 'Documents',
      })

      await Share.open({
        url: `file://${pdf.filePath}`,
        type: 'application/pdf',
        title: 'Demand Letter',
      })
    } catch (e: any) {
      if (!e.message?.includes('User did not share') && !e.message?.includes('cancel')) {
        Alert.alert('Export unavailable', 'PDF export requires a physical device. Copy the letter text manually.')
      }
    }
    setGeneratingPdf(false)
  }

  return (
    <View style={styles.container}>
      <SafeAreaView>
        <View style={styles.toolbar}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Text style={styles.backText}>← Back</Text>
          </TouchableOpacity>
          <Text style={styles.toolbarTitle}>📝 Demand Letter</Text>
          <View style={{ width: 80 }} />
        </View>
      </SafeAreaView>

      <ScrollView style={styles.letterContainer}>
        <View style={styles.letterPaper}>
          {letter.split('\n').map((line, i) => (
            <Text key={i} style={line.trim() ? styles.letterLine : styles.letterSpacer}>
              {line || ' '}
            </Text>
          ))}
          <Text style={styles.letterDisclaimer}>
            {'\n\n---\n'}
            This letter was prepared using publicly available legal information by Advocate App.
            It does not constitute legal advice. For complex matters, consult a licensed attorney.
          </Text>
        </View>
      </ScrollView>

      <View style={styles.tips}>
        <Text style={styles.tipsTitle}>📮 Sending Tips</Text>
        <Text style={styles.tipText}>• Send via certified mail for legal proof of delivery</Text>
        <Text style={styles.tipText}>• Keep a copy for your records</Text>
        <Text style={styles.tipText}>• Follow up in 7–14 days if no response</Text>
      </View>

      <TouchableOpacity
        style={styles.exportWrapper}
        onPress={handleExport}
        activeOpacity={0.9}
        disabled={generatingPdf}
      >
        <LinearGradient
          colors={colors.gradientGold as [string, string, string]}
          style={styles.exportButton}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 0 }}
        >
          {generatingPdf
            ? <ActivityIndicator color="#FFF" size="small" />
            : <Text style={styles.exportText}>📤 Export PDF</Text>
          }
        </LinearGradient>
      </TouchableOpacity>
    </View>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bgScreen },
  toolbar: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: 20, paddingVertical: 14,
    borderBottomWidth: 1, borderBottomColor: colors.border,
  },
  backText: { color: colors.primary, fontSize: 15 },
  toolbarTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
  exportWrapper: { borderRadius: 18, overflow: 'hidden', margin: 16 },
  exportButton: { paddingVertical: 18, alignItems: 'center' },
  exportText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
  letterContainer: { flex: 1 },
  letterPaper: {
    margin: 16, backgroundColor: '#FFFFFF', borderRadius: 12,
    padding: 28, shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 8, elevation: 4,
  },
  letterLine: { fontSize: 14, color: '#1a1a1a', lineHeight: 24, marginBottom: 2 },
  letterSpacer: { fontSize: 14, color: '#1a1a1a', lineHeight: 16 },
  letterDisclaimer: { fontSize: 11, color: '#888', lineHeight: 16, marginTop: 8 },
  tips: {
    backgroundColor: 'rgba(255,255,255,0.06)', borderTopWidth: 1, borderTopColor: colors.border,
    padding: 20,
  },
  tipsTitle: { fontSize: 14, fontWeight: '700', color: colors.text, marginBottom: 10 },
  tipText: { fontSize: 13, color: 'rgba(255,255,255,0.55)', marginBottom: 6, lineHeight: 20 },
})
