import React from 'react'
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Linking } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { colors } from '../theme/colors'

const LAST_UPDATED = 'March 13, 2026'
const CONTACT_EMAIL = 'legal@advocate-app.com'
const WEB_URL = 'https://advocate-app.netlify.app/terms-of-service'

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <View style={styles.section}>
    <Text style={styles.sectionTitle}>{title}</Text>
    {children}
  </View>
)

const Body = ({ children, style }: { children: string; style?: object }) => (
  <Text style={[styles.body, style]}>{children}</Text>
)

const Bullet = ({ children }: { children: string }) => (
  <Text style={styles.bullet}>• {children}</Text>
)

export default function TermsOfServiceScreen({ navigation }: any) {
  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.back}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Terms of Service</Text>
        <Text style={styles.updated}>Last updated: {LAST_UPDATED}</Text>
        <TouchableOpacity onPress={() => Linking.openURL(WEB_URL)}>
          <Text style={styles.webLink}>View online ↗</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.content}>

        <View style={styles.warningBox}>
          <Text style={styles.warningTitle}>⚖️ NOT LEGAL ADVICE</Text>
          <Text style={styles.warningText}>
            Advocate provides legal information and educational content only. Nothing in this app constitutes legal advice, creates an attorney-client relationship, or should be relied upon as a substitute for professional legal counsel. For important legal matters, always consult a licensed attorney in your jurisdiction.
          </Text>
        </View>

        <Section title="1. Acceptance of Terms">
          <Body>
            By downloading, installing, or using Advocate ("the App"), you agree to be bound by these Terms of Service. If you do not agree, do not use the App.
          </Body>
        </Section>

        <Section title="2. Description of Service">
          <Body>
            Advocate is an AI-powered consumer rights information tool that helps users understand their general legal rights, draft demand letters, and prepare for communications with opposing parties. The App uses artificial intelligence to generate content based on publicly available legal information.
          </Body>
        </Section>

        <Section title="3. Not Legal Advice — Important Disclaimer">
          <Body>
            YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT:
          </Body>
          <Bullet>Advocate is NOT a law firm and does not provide legal advice</Bullet>
          <Bullet>No attorney-client relationship is formed by using this App</Bullet>
          <Bullet>AI-generated content may be incomplete, inaccurate, or not applicable to your specific situation</Bullet>
          <Bullet>Laws vary by jurisdiction and change over time — always verify information independently</Bullet>
          <Bullet>You should consult a licensed attorney for any significant legal matter</Bullet>
          <Bullet>The App's output is for informational and educational purposes only</Bullet>
        </Section>

        <Section title="4. User Responsibilities">
          <Body>You agree to:</Body>
          <Bullet>Use the App only for lawful purposes</Bullet>
          <Bullet>Provide accurate information when describing your situation</Bullet>
          <Bullet>Not use the App to harass, threaten, or harm others</Bullet>
          <Bullet>Not attempt to reverse-engineer or misuse the App</Bullet>
          <Bullet>Take sole responsibility for decisions made based on App content</Bullet>
          <Bullet>Not use the App for frivolous or bad-faith legal claims</Bullet>
        </Section>

        <Section title="5. Subscriptions and Payments">
          <Body>
            Advocate offers free and paid subscription tiers. Subscriptions are managed through RevenueCat and processed by Apple App Store or Google Play Store.
          </Body>
          <Bullet>Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date</Bullet>
          <Bullet>Manage or cancel your subscription in your device's app store account settings</Bullet>
          <Bullet>Refunds are subject to Apple/Google's refund policies</Bullet>
          <Bullet>Prices may change with reasonable notice</Bullet>
        </Section>

        <Section title="6. AI-Generated Content">
          <Body>
            Content generated by the App is produced by AI models and may contain errors, omissions, or outdated information. We make no warranties regarding the accuracy, completeness, or fitness for purpose of any AI-generated content. Do not submit demand letters or take legal action solely based on App output without independent verification.
          </Body>
        </Section>

        <Section title="7. Intellectual Property">
          <Body>
            The App, its design, logo, and software are owned by Advocate and protected by applicable intellectual property laws. You are granted a limited, non-exclusive, non-transferable license to use the App for personal purposes. You retain ownership of the content you input; you grant us a license to process it to provide the service.
          </Body>
        </Section>

        <Section title="8. Limitation of Liability">
          <Body>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, ADVOCATE AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE APP, INCLUDING BUT NOT LIMITED TO:
          </Body>
          <Bullet>Reliance on AI-generated legal information</Bullet>
          <Bullet>Outcomes of legal disputes or negotiations</Bullet>
          <Bullet>Loss of data or unauthorized access</Bullet>
          <Bullet>Any legal proceedings you initiate based on App content</Bullet>
          <Body style={{ marginTop: 8 }}>
            Our total liability to you shall not exceed the amount you paid for the App in the 12 months preceding the claim.
          </Body>
        </Section>

        <Section title="9. Indemnification">
          <Body>
            You agree to indemnify and hold harmless Advocate and its operators from any claims, damages, or expenses (including legal fees) arising from your use of the App, violation of these Terms, or infringement of any third-party rights.
          </Body>
        </Section>

        <Section title="10. Termination">
          <Body>
            We reserve the right to suspend or terminate your account for violations of these Terms. You may delete your account at any time from Settings. Upon termination, your right to use the App ceases immediately.
          </Body>
        </Section>

        <Section title="11. Governing Law">
          <Body>
            These Terms are governed by the laws of India for users in India, and the laws of the State of Delaware, USA for all other users, without regard to conflict of law principles. Disputes shall be resolved by binding arbitration, except where prohibited by law.
          </Body>
        </Section>

        <Section title="12. Changes to Terms">
          <Body>
            We may update these Terms at any time. Continued use of the App after changes constitutes acceptance. We will notify you of material changes via the App.
          </Body>
        </Section>

        <Section title="13. Contact">
          <Body>For questions about these Terms, contact:</Body>
          <Text style={styles.email}>{CONTACT_EMAIL}</Text>
        </Section>

      </ScrollView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container:    { flex: 1, backgroundColor: colors.bgScreen },
  header:       { padding: 24, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: colors.border },
  back:         { color: colors.primary, fontSize: 16, marginBottom: 12 },
  title:        { fontSize: 26, fontWeight: '800', color: colors.text },
  updated:      { fontSize: 13, color: colors.textMuted, marginTop: 4 },
  scroll:       { flex: 1 },
  content:      { padding: 24, paddingBottom: 60 },
  warningBox: {
    backgroundColor: colors.goldPrimary + '18',
    borderRadius: 12, padding: 16,
    borderWidth: 1, borderColor: colors.goldPrimary + '50',
    marginBottom: 24,
  },
  warningTitle: { fontSize: 15, fontWeight: '800', color: colors.goldPrimary, marginBottom: 8 },
  warningText:  { fontSize: 14, color: colors.text, lineHeight: 22 },
  section:      { marginBottom: 28 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: colors.goldPrimary, marginBottom: 10 },
  body:         { fontSize: 14, color: colors.textSecondary, lineHeight: 22, marginBottom: 8 },
  bullet:       { fontSize: 14, color: colors.textSecondary, lineHeight: 22, marginBottom: 4, paddingLeft: 8 },
  email:        { fontSize: 15, color: colors.primary, fontWeight: '600', marginTop: 4 },
  webLink:      { fontSize: 13, color: colors.primary, marginTop: 4 },
})
